on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'printing folder content'
        run: ls

      - name: 'testing printing'
        run: echo yousef


